name: Deploy GitHub page

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
    branches:
      - main

jobs:
  deploy-gh-page:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Initialize npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build

      - name: Deploy GitHub page
        working-directory: ./build
        run: |-
            git init
            git config --local user.name ${{ github.repository_owner }}
            git config --local user.email ${{ github.repository_owner }}@users.noreply.github.com
            git add .
            git commit -m "deploy: ${{ github.sha }}"
            git remote add -f origin https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git checkout gh-pages
            git pull
            git cherry-pick master -X theirs
            git push
